project:
  type: website
  # output-dir: docs
execute: 
  freeze: auto  # Re-render only when source changes
  cache: true

website:
  title: "MyLabJournal"
  favicon: assets/icons/favicon.svg
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Journal"
        menu: 
          - text: "01 Challenge1_Machine_Learning_Fundamentals"
            file: content/01_journal/01_Challenge1_Machine_Learning_Fundamentals.qmd
          - text: "02_Challenge2_Supervised_ML-Regression2"
            file: content/01_journal/02_Challenge2_Supervised_ML-Regression2.qmd
          - text: "03 Challenge3_automated_machine_learning_with_h20_1"
            file: content/01_journal/03_Challenge3_automated_machine_learning_with_h20_1.qmd
          - text: "04 Challenge4_performance_measures"
            file: content/01_journal/04_Challenge4_performance_measures.qmd
          - text: "05 Challenge5_Explaining_Black-Box_Models_With_LIME"
            file: content/01_journal/05_Challenge5_Explaining_Black-Box_Models_With_LIME.qmd            
      - text: "Class notes"
        file: content/02_notes/05_class_notes.qmd
      - text: "Links"
        file: content/03_other/06_links.qmd

format:
  html:
    theme:
      dark: darkly
      light: flatly
    highlight-style: a11y-dark
filters:
   - lightbox
lightbox: auto